<?php

/**
 * @file
 * Extending the CAPTCHA module with dansih language audio support.
 */

/**
 * Implements hook_help().
 */
function bibdkcaptcha_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/modules#name':
      $output .= t('Bibdk Captcha');
      break;
    case 'admin/modules#description':
    case 'admin/user/captcha/bibdkcaptcha':
      break;
    case 'admin/help#bibdkcaptcha':
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 */
function bibdkcaptcha_menu() {
  $items = array();
  $items['admin/config/people/captcha/bibdkcaptcha'] = array(
    'title' => 'bibdkcaptcha',
    'description' => 'Administer the reCAPTCHA web service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recaptcha_admin_settings'),
    'access arguments' => array('administer recaptcha'),
    'type' => MENU_LOCAL_TASK,
      #'file' => 'recaptcha.admin.inc',
  );

  $items['user/create_login/refreshcatptcha'] = array(
    'page callback' => 'bibdkcaptcha_callback_test',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implementation of hook_captcha().
 * 
 */
function bibdkcaptcha_captcha($op, $captcha_type = '', $sid = NULL) {
  dpm('bibdk captcha');
  drupal_add_js(drupal_get_path('module', 'bibdkcaptcha') . '/bibdkcaptcha.js');
  switch ($op) {
    case 'list':
      return array('Bibdk Captcha');
    case 'generate':
      if ($captcha_type == 'Bibdk Captcha') {
        $captcha = image_captcha_captcha($op, 'Image', $sid);
        generateSoundFile($captcha['solution']);
        $markup = _append_buttons($captcha['form']['captcha_image']['#markup']);
        $captcha['form']['captcha_image']['#markup'] = $markup;
        return $captcha;
      }
      break;
  }
}

function _append_buttons($markup) {
  $module_path = base_path() . drupal_get_path('module', 'bibdkcaptcha');
  $refresh_btn = $module_path . '/graphics/refresh.gif';
  $audio_btn = $module_path . '/graphics/audio_icon.gif';
  $markup = $markup . '<br/><img id="refreshbtn" src="' . $refresh_btn . '"/>
    <img id="audiobtn" src="' . $audio_btn . '"/>';
  return $markup;
}

function generateSoundFile($solution) {
  dpm($solution);
}

function bibdkcaptcha_callback_test() {
  $data = 'string sent from PHP';
  drupal_json_output($data);
}